theme = "flatwhite"

[editor]
auto-save = true # auto save when lose focus
bufferline = "multiple"
mouse = false
line-number = "relative"
color-modes = true
cursorline = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "read-only-indicator"]
right = ["register", "diagnostics", "version-control", "selections", "position"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true


[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.indent-guides]
render = true # add vertical lines for indentation

# change it so d and c don't yank
[keys.normal]
A-d = "delete_selection"
d = "delete_selection_noyank"
A-c = "change_selection"
c = "change_selection_noyank"
